let items = [
    ["Adaptive Control Unit", 50, 0, false, false],
    ["AI Limiter", 100, 0, false, false],
    ["Alclad Aluminum Sheet", 200, 0, false, false],
    ["Alien Carapace", 50, 0, false, false],
    ["Alien DNA Capsule", 50, 0, false, false],
    ["Alien Organs", 50, 0, false, false],
    ["Alien Protien", 10, 0, false, false],
    ["Alien Remains", 50, 0, false, false],
    ["Alumina Solution", 0, 0, false, true],
    ["Aluminum Casing", 200, 0, false, false],
    ["Aluminum Ingot", 100, 0, false, false],
    ["Aluminum Scrap", 500, 0, false, false],
    ["Assembly Director System", 50, 0, false, false],
    ["Automated Wiring", 50, 0, false, false],
    ["Battery", 200, 0, false, false],
    ["Bauxite", 100, 0, true, false],
    ["Beacon", 100, 0, false, false],
    ["Biomass", 200, 0, false, false],
    ["Black Powder", 200, 0, false, false],
    ["Cable", 200, 0, false, false],
    ["Caterium Ore", 100, 0, true, false],
    ["Caterium Ingot", 100, 0, false, false],
    ["Circuit Board", 200, 0, false, false],
    ["Coal", 100, 0, true, false],
    ["Color Cartridge", 500, 0, false, false],
    ["Compacted Coal", 100, 0, false, false],
    ["Computer", 50, 0, false, false],
    ["Concrete", 500, 0, false, false],
    ["Cooling System", 100, 0, false, false],
    ["Copper Ingot", 100, 0, false, false],
    ["Copper Ore", 100, 0, true, false],
    ["Copper Powder", 500, 0, false, false],
    ["Copper Sheet", 200, 0, false, false],
    ["Crude Oil", 0, 0, true, true],
    ["Crystal Oscillator", 100, 0, false, false],
    ["Electromagnetic Control Rod", 100, 0, false, false],
    ["Empty Canister", 100, 0, false, false],
    ["Empty Fluid Tank", 100, 0, false, false],
    ["Encased Industrial Beam", 100, 0, false, false],
    ["Encased Plutonium Cell", 200, 0.3, false, false],
    ["Encased Uranium Cell", 200, 0.3, false, false],
    ["Fabric", 100, 0, false, false],
    ["Flower Petals", 500, 0, true, false],
    ["Fuel", 0, 0, false, true],
    ["Fused Modular Frame", 50, 0, false, false],
    ["Heat Sink", 100, 0, false, false],
    ["Heavy Modular Frame", 50, , 0, false, false],
    ["Heavy Oil Residue", 0, 0, false, true],
    ["High-Speed Connector", 100, 0, false, false],
    ["Iron Ingot", 100, 0, false, false],
    ["Iron Ore", 100, 0, true, false],
    ["Iron Plate", 200, 0, false, false],
    ["Iron Rod", 200, 0, false, false],
    ["Iron Rebar", 100, 0, false, false],
    ["Leaves", 500, 0, true, false],
    ["Limestone", 100, 0, true, false],
    ["Liquid Biofuel", 0, 0, false, true],
    ["Magnetic Field Generator", 50, 0, false, false],
    ["Modular Engine", 50, 0, false, false],
    ["Modular Frame", 50, 0, false, false],
    ["Motor", 50, 0, false, false],
    ["Mycelia", 200, 0, true, false],
    ["Nitric Acid", 0, 0, false, true],
    ["Nitrogen Gas", 0, 0, false, true],
    ["Non-Fissile Uranium", 500, 0.2, false, false],
    ["Nuclear Pasta", 50, 0, false, false],
    ["Packaged Alumina Solution", 100, 0, false, false],
    ["Packaged Fuel", 100, 0, false, false],
    ["Packaged Heavy Oil Residue", 100, 0, false, false],
    ["Packaged Liquid Biofuel", 100, 0, false, false],
    ["Packaged Nitric Acid", 100, 0, false, false],
    ["Packaged Nitrogen Gas", 100, 0, false, false],
    ["Packaged Oil", 100, 0, false, false],
    ["Packaged Sulfiric Acid", 100, 0, false, false],
    ["Packaged Turbofuel", 100, 0, false, false],
    ["Packaged Water", 100, 0, false, false],
    ["Petroleum Coke", 200, 0, false, false],
    ["Plastic", 200, 0, false, false],
    ["Plutonium Fuel Rod", 50, 0.2, false, false],
    ["Plutonium Pellet", 100, 0.2, false, false],
    ["Plutonium Waste", 500, 0.2, false, false],
    ["Polymer Resin", 200, 0, false, false],
    ["Pressure Conversion Cube", 50, , 0, false, false],
    ["Quantm Computer", 50, 0, false, false],
    ["Quartz Crystal", 200, 0, false, false],
    ["Quickwire", 500, 0, false, false],
    ["Radio Control Unit", 50, 0, false, false],
    ["Raw Quartz", 100, 0, true, false],
    ["Reinforced Iron Plate", 100, 0, false, false],
    ["Rotor", 100, 0, false, false],
    ["Rubber", 200, 0, false, false],
    ["Screw", 500, 0, false, false],
    ["Silica", 200, 0, false, false],
    ["Smart Plating", 50, 0, false, false],
    ["Smokeless Powder", 100, 0, false, false],
    ["Solid Biofuel", 200, 0, false, false],
    ["Stator", 100, 0, false, false],
    ["Steel Beam", 200, 0, false, false],
    ["Steel Ingot", 100, 0, false, false],
    ["Steel Pipe", 200, 0, false, false],
    ["Sulfiric Acid", 0, 0, false, true],
    ["Sulfur", 100, 0, true, false],
    ["Supercomputer", 50, 0, false, false],
    ["Superposition Oscillator", 100, 0, false, false],
    ["Thermal Propulsion Rocket", 50, 0, false, false],
    ["Turbo Motor", 50, 0, false, false],
    ["Turbofuel", 0, 0, false, true],
    ["Uranium", 100, 0.4, true, false],
    ["Uranium Fuel Rod", 50, 0.4, false, false],
    ["Uranium Waste", 500, 0.4, false, false],
    ["Versatile Framework", 50, 0.4, false, false],
    ["Water", 0, 0, false, true],
    ["Wire", 500, 0, false, false],
    ["Wood", 200, 0, true, false],
]